language: 'node_js'
node_js:
  - '10'
cache:
  directories:
    - 'node_modules'
script:
  - 'cross-env NODE_ICU_DATA=node_modules/full-icu npm run test'
after_script:
  - 'cat ./coverage/lcov.info | coveralls'
git:
  submodules: false
